sudo: false
language: node_js
node_js:
  - "5"
  - "4"
before_script: npm run external-deps
script:
  - npm run eslint
  - npm run scsslint
  - npm run coverage
  - npm run build-all
  - node node/loader.js
after_success:
  - npm run report-coverage
