sudo: false
language: node_js
node_js:
  - "5"
  - "4"
before_script: npm run external-deps
script:
  - npm run lint
  - nyc npm test
  - npm run build -- node
  - node dist/node/loader.js
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
