sudo: false
language: node_js
node_js:
  - "5"
  - "4"
before_script: npm run external-deps
script:
  - npm run lint
  - npm test
  - npm run build -- node
  - cd dist/node
  - npm i
  - node loader.js
